image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      git clone https://github.com/input-output-hk/plutus-pioneer-program || (cd plutus-pioneer-program ; git pull)
    command: cd plutus-pioneer-program/code

vscode:
  extensions:
    - haskell.haskell
    - s0kil.vscode-hsx
    - arrterian.nix-env-selector